engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript: true
        python:
          python_version: 3
    checks:
      Similar code:
        enabled: false
  # eslint:
    # enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - BUG
        - FIXME
        - HACK
        # - NOTE
        # - TODO
        - XXX
  markdownlint:
    enabled: true
    checks:
      MD012:
        enabled: false
  # nodesecurity:
    # enabled: true
  # pep8:
    # enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "D"
  # stylelint:
    # enabled: true
ratings:
  paths:
    - "**.md"
    - "**.py"
exclude_paths:
  - tests/
