engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        python:
          python_version: 3
  # eslint:
    # enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - BUG
        - CUSTOM
        - FIXME
  markdownlint:
    enabled: true
  # nodesecurity:
    # enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "D"
  stylelint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.less"
    - "**.md"
    - "**.py"
exclude_paths:
  - tests/
