sudo: required
language: python
env:
  global:
    - secure: "bYWv6YwvjwAuP9lQbAx4vAUx/CSX1XVLysUr02RDylUOMfYdrRmm4WGpV03eA2miX1RdSOI+dQDMEyFUUhV0hhHR3dl4oRJ1XEVupaFAfxYQJWL/u7FoJ2QK5gTx3rOSH0fDgEPaSiQyHz84aQS0E8QLO/JQQxJIqjDTo4JAikY="
branches:
  only:
    - master
    - coverity_scan
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  # - "pypy3"
matrix:
  allow_failures:
    - "2.6"
    - "nightly"
    - "pypy"
    # - "pypy3"
  fast_finish: true
cache: pip
before_install:
  - sudo apt-get -qq update
  # - sudo apt-get install -y pandoc
  - sudo apt-get install -y python-crypto
  - sudo apt-get install -y python-pycurl
before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
  - pip install -U setuptools
  # - pip install coveralls
  # - pip install scrutinizer-ocular
  - pip install tox-travis
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then tox --skip-missing-interpreters ; fi
# after_success:
  # - coveralls
  # - ocular
addons:
  coverity_scan:
    project:
      name: "pyload/pyload"
      description: "Free and Open Source download manager written in Pure Python and designed to be extremely lightweight, fully customizable and remotely manageable"
    notification_email: dev@pyload.net
    build_command_prepend: ""
    build_command: "python setup.py configure"
    branch_pattern: coverity_scan
# deploy:
  # provider: pypi
  # distributions: sdist bdist_wheel
  # user: vuolter
  # password:
    # secure:
  # on:
    # tags: true
    # repo: pyload/pyload
    # condition:
