sudo: required
language: python
branches:
  only: master
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  # PyPy versions
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - "2.6"
    - "nightly"
    - "pypy"
    - "pypy3"
  fast_finish: true
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-crypto
  - sudo apt-get install -y python-pycurl
install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install tox-travis
script:
  - tox --develop --skip-missing-interpreters
after_success:
  - coveralls
